### ISSUE TITLE
http errors & not transferring

### ISSUE THREAD

**Issue by TraciBunkers** [agentile/S3-Media-Storage#8] opened 2014-03-25 13:10 UTC
I updated the plugin to the new version 1.0.3, made the change in admin.php so I could see the settings, but I'm still having http errors and the files aren't automatically transferring. I think I mentioned this before-- when I try to upload an image and get the http error, although it does upload to my media library, the thumbnail doesn't show. When I turn off the plugin, I can upload w/ no problem & see the thumbnails in the media library. But for the images I've transferred to S3 with the plugin, those thumbnails don't show in the admin or on my site.

**Comment by agentile** [comment] 2014-03-25 17:37
Hi @TraciBunkers , is your site using an SSL cert? If so there can be some issues if your SSL installation was not properly done ... aka curl not do a verify host or peer. If this is the case, you can edit line 112 of S3.php to be false instead of true.

**Comment by TraciBunkers** [comment] 2014-03-25 17:46
Yes, I use an SSL cert. I made the change on line 112, and just tested it. The first image I uploaded worked. But the next 3 didn't--I got http errors on them, and they didn't transfer to S3.

**Comment by agentile** [comment] 2014-03-25 17:51
unless you want to give me access to your setup to inspect what is going on, I think you would need to do some additional debugging yourself to find out what the root cause is. Doing things like changing line 429 of s3-media-storage.php from 

``` php
        } catch (Exception $e) {}
```

to 

``` php
        } catch (Exception $e) { echo $e->getMessage(); }
```

and/or checking the ajax response using something like firebug.

**Comment by TraciBunkers** [comment] 2014-03-25 18:00
Okay, I put in the code on 429 tried uploading, and here's what I got:
S3::putObject(): [6] Could not resolve host: MY-BUCKET.s3.amazonaws.comS3::putObject(): [6] Could not resolve host: MY-BUCKET.s3.amazonaws.comS3::putObject(): [6] Could not resolve host: MY-BUCKET.s3.amazonaws.comS3::putObject(): [6] Could not resolve host: MY-BUCKET.s3.amazonaws.com4630

**Comment by agentile** [comment] 2014-03-25 18:14
Your bucket name is MY-BUCKET? My guess is that you didn't actually setup an S3 bucket? If you did, it needs to be the corresponding bucket name for e.g. My bucket name is s3mediastorage which in turn maps to http://s3mediastorage.s3.amazonaws.com

where assets are stores e.g. http://s3mediastorage.s3.amazonaws.com/blog/2014/03/anthony-gentile-120-square.jpg

If you do actually have the bucket name MY-BUCKET ... then the error is telling you that it can't connect to it, maybe you need to lower case it to my-bucket as when I try to go to MY-BUCKET.s3.amazonaws.com it redirect me to my-bucket.s3.amazonaws.com ... this redirect could be what is causing the issue.

**Comment by agentile** [comment] 2014-03-25 18:37
Oh ... sorry I assumed incorrectly, should have figured that you changed it.

Hmmm ... a could not resolve host error .... is your site hosted on an EC2? if so, are the locations different for the S3 bucket and the EC2? (really it shouldn't matter, but I'm just suggesting things I am finding on google) ... is your server's time correct (using something like ntp to keep it correct time), I've had issues in the past where I could not upload to S3 because the server time was different from what amazon was expecting.

The issue is this could not resolve host error, so we need to figure out why your server can't connect to the S3 bucket in this particular scenario.

**Comment by TraciBunkers** [comment] 2014-03-25 18:37
I just tried again, and don't always get the error about not being able to resolve host--sometimes it's just the http error.

**Comment by TraciBunkers** [comment] 2014-03-25 18:42
No, I'm not on EC2. How can I check if my server's time is correct?

**Comment by agentile** [comment] 2014-03-25 18:53
You can type `date` into your server's terminal to see what the current system time is. To have it always be in sync with atomic clocks you would want to install `ntp` a quick google search will help you there e.g. http://www.cyberciti.biz/faq/howto-install-ntp-to-synchronize-server-clock/

**Comment by TraciBunkers** [comment] 2014-03-25 18:56
I don't know if this will help any with this issue, but I was having a problem with digital downloads with my e-commerce plugin. My host figured out that one of the files for that plugin had $buffer = fread($file, $packet); 
and the server (CloudLinux) didn't like the $packet because it uses software to prevent abuse. He changed that line to 
$buffer = fread($file, 4096);
And that fixed it.

**Comment by TraciBunkers** [comment] 2014-03-25 19:03
In my cpanel. I don't see where to check the server's time, so I'll have to sub,it a support request with my host to find out. I'm assuming it would be correct.

**Comment by TraciBunkers** [comment] 2014-03-25 21:35
I submitted a ticket to my web host asking about the time, and the tech pointed me to this: http://us3.php.net/date_default_timezone_set
So, I don't know what time the server is using.

**Comment by agentile** [comment] 2014-06-01 17:56
Closing, thanks.

**Closed as completed by agentile** 2014-06-01 17:56 UTC

**Comment by TraciBunkers** [comment] 2014-06-01 20:34
I never got this working :(
